### ISSUE TITLE
Import doesnt work

### ISSUE THREAD

**Issue by segura2010** [stoffern/pokemon-go-api#1]
/pokemon-go-api/example/example.js:1
(function (exports, require, module, __filename, __dirname) { import PokeAPI from '../src'
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3

**Comment by stoffern** [comment]
it is ES6.. you need to run it with babel..
